"""sync_schema_pipeline_runs_and_foreign_keys

Revision ID: 6f9d505eaa6c
Revises: 82dfbffcffc4
Create Date: 2026-09-13 14:05:43.864635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9d505eaa6c'
down_revision: Union[str, Sequence[str], None] = '82dfbffcffc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'agent_runs', 'pipeline_runs', ['pipeline_run_id'], ['id'])
    op.alter_column('assets', 'prompt',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('assets', 'negative_prompt',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('assets', 'workflow',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'assets', 'pipeline_runs', ['pipeline_run_id'], ['id'])
    op.create_foreign_key(None, 'content', 'content_batches', ['batch_id'], ['id'])
    op.alter_column('pipeline_runs', 'reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'research', 'pipeline_runs', ['pipeline_run_id'], ['id'])
    op.create_foreign_key(None, 'scenes', 'pipeline_runs', ['pipeline_run_id'], ['id'])
    op.create_foreign_key(None, 'scripts', 'pipeline_runs', ['pipeline_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scripts', type_='foreignkey')
    op.drop_constraint(None, 'scenes', type_='foreignkey')
    op.drop_constraint(None, 'research', type_='foreignkey')
    op.alter_column('pipeline_runs', 'reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.alter_column('assets', 'workflow',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assets', 'negative_prompt',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assets', 'prompt',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'agent_runs', type_='foreignkey')
    # ### end Alembic commands ###
