"""add_ix_one_active_job_per_content

Revision ID: c5a1a628620f
Revises: 6f9d505eaa6c
Create Date: 2026-09-13 20:26:50.556318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a1a628620f'
down_revision: Union[str, Sequence[str], None] = '6f9d505eaa6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clean up any legacy jobs that lack pipeline_run_id before enforcing NOT NULL
    op.execute("DELETE FROM pipeline_jobs WHERE pipeline_run_id IS NULL OR pipeline_run_id NOT IN (SELECT id FROM pipeline_runs)")
    # Resolve any existing duplicate active jobs by marking older active jobs as failed
    op.execute("""
        UPDATE pipeline_jobs 
        SET status = 'failed', error = 'superseded' 
        WHERE status IN ('queued', 'running', 'resuming') 
        AND id NOT IN (
            SELECT DISTINCT ON (content_id) id 
            FROM pipeline_jobs 
            WHERE status IN ('queued', 'running', 'resuming') 
            ORDER BY content_id, created_at DESC
        )
    """)
    op.alter_column('pipeline_jobs', 'pipeline_run_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('ix_one_active_job_per_content', 'pipeline_jobs', ['content_id'], unique=True, postgresql_where="status IN ('queued', 'running', 'resuming')")
    op.create_foreign_key(None, 'pipeline_jobs', 'pipeline_runs', ['pipeline_run_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pipeline_jobs', type_='foreignkey')
    op.drop_index('ix_one_active_job_per_content', table_name='pipeline_jobs', postgresql_where="status IN ('queued', 'running', 'resuming')")
    op.alter_column('pipeline_jobs', 'pipeline_run_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
